apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-all-tasks-job
spec:
  template:
    spec:
      containers:
      - name: fetch-tasks
        image: curlimages/curl:latest
        command: ["curl", "-X", "GET", "http://task-scheduler-service:5000/tasks/"]
      restartPolicy: Never
