apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-scheduler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-scheduler
  template:
    metadata:
      labels:
        app: task-scheduler
    spec:
      containers:
      - name: task-scheduler
        image: uweeds/task-scheduler:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: task-scheduler-service
spec:
  type: ClusterIP
  selector:
    app: task-scheduler
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
